env: "prod" # prod

jwt:
  app_secret_a: "1YAJoxPSVW-W26tGD4x3WRCBW3-px2PQfUbZqzR8YC8" # секретный ключ для дешифрования access токенов

grpc:
  port: 50051
  timeout: "5s" # время обработки запроса 

POSTGRES:
  POSTGRES_HOST: database_Canvas  # Имя сервиса в Docker Compose
  POSTGRES_PORT: 5432
  POSTGRES_USER: "admin"
  POSTGRES_PASS: "admin"
  POSTGRES_DB: "test_db"
  POSTGRES_SSLMODE: disable
  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5

MINIO:
  MINIO_HOST: minio # Имя сервиса в Docker Compose
  MINIO_PORT: 9000
  MINIO_USER: "minio"
  MINIO_PASS: "minio123"
  MINIO_BUCKET: "canvases"
  MINIO_SSLMODE: true

KAFKA:
  KAFKA_BROKERS:
    - "kafka1:19092"
    - "kafka2:19093"
    - "kafka3:19094"
  KAFKA_TOPIC: "joinToCanvas"